TimeManagementTool/TimeManagementTool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('TimeManagementToolApp.urls')),
]

TimeManagementTool/TimeManagementToolApp/urls.py
from django.urls import path
from . import views

app_name = 'TimeManagementToolApp'
urlpatterns = [
    #etusivu
    path('', views.index, name='index'),
    #kurssit-sivu
    path('kurssit/', views.kurssit, name='kurssit'),
    #Valitun kurssin oma sivu
    path('kurssit/<int:kurssi_id>/', views.kurssi, name='kurssi'),
     #Lisää kurssi -sivu
    path('kurssit/lisaa_kurssi', views.lisaa_kurssi, name='lisaa_kurssi'),
    #Muokkaa tehtävää sivu
    path('muokkaa_tehtava/<int:teht_id>', views.muokkaa_tehtava, name='muokkaa_tehtava'),
    #Lisää tehtävä -sivu
    path('lisaa_tehtava/<int:kurssi_id>/', views.lisaa_tehtava, name='lisaa_tehtava'),
    #Poista tehtävä
    path('tehtava/poista/<int:teht_id>/', views.poista_tehtava, name='poista_tehtava'),
    #Poista kurssi
    path('kurssi/poista/<int:kurssi_id>/', views.poista_kurssi, name='poista_kurssi'),


]

TimeManagementTool/accounts/urls.py
#url patternit käyttäjille

from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    #rekisteröintisivu
    path('rekist/', views.rekist, name='rekist'),
]

TimeManagementTool/TimeManagementToolApp/models.py
from django.db import models
from django.contrib.auth.models import User

# mallit

class Kurssi(models.Model):
    #kurssi, jonka tehtävä kyseessä
    kurssi = models.CharField(max_length=200)
    kayttaja = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name_plural = 'Kurssit'

    def __str__(self):
        return self.kurssi


class Teht(models.Model):
    #kurssin tehtävänanto
    kurssi = models.ForeignKey(Kurssi, on_delete=models.CASCADE)
    teht = models.TextField()
    dedis = models.DateTimeField(null=True)
    valmis = models.BooleanField(null=True)


    class Meta:
        verbose_name_plural = 'Tehtavat'

    def __str__(self):
        return f"{self.teht[:50]}"

TimeManagementTool/accounts/models.py
from django.db import models

# Create your models here.

TimeManagementTool/TimeManagementToolApp/forms.py
from django import forms

from .models import Kurssi, Teht

class KurssiForm(forms.ModelForm):
    class Meta:
        model = Kurssi
        fields = ['kurssi']
        labels = {'kurssi': ''}

class TehtForm(forms.ModelForm):

    class Meta:
        model = Teht
        #valmis = forms.BooleanField(initial = True, required = False)
        fields = ['teht', 'dedis', 'valmis']
        labels = {'teht': ''}
        widgets = {'dedis': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'})}

TimeManagementTool/TimeManagementToolApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Kurssi, Teht
from django.db.models.functions import Lower
from .forms import KurssiForm, TehtForm
from django.http import Http404

# Create your views here.

@login_required
def index(request):
    #etusivu ajanhallinnalle
    kurssit = Kurssi.objects.filter(kayttaja=request.user).order_by(Lower('kurssi'))
    #järjestää kurssit aakkosjärjestykseen huomioiden myös pienet alkukirjaimet
    return render(request, 'TimeManagementToolApp/index.html',{'kurssit': kurssit})

@login_required
def kurssit(request):
    #kaikki kurssit
    kurssit = Kurssi.objects.filter(kayttaja=request.user).order_by(Lower('kurssi')) 
    context = {'kurssit': kurssit}
    return render(request, 'TimeManagementToolApp/kurssit.html', context)

@login_required
def kurssi(request, kurssi_id):
    #yhden kurssin lisätyt tehtävät
    kurssi = Kurssi.objects.get(id=kurssi_id)
    #varmistetaan, että kurssi kuuluu käyttäjälle
    if kurssi.kayttaja != request.user:
        raise Http404
    tehtavat = kurssi.teht_set.order_by('teht')
    context = {'kurssi': kurssi, 'teht': tehtavat}
    return render(request, 'TimeManagementToolApp/kurssi.html', context)

@login_required
def lisaa_kurssi(request):
    #Lisää uusi kurssi
    if request.method != 'POST':
        #Luodaan tyhjä lomake
        form = KurssiForm()

    else:
        #Käsitellään data
        form = KurssiForm(data=request.POST)
        if form.is_valid():
            lisaa_kurssi = form.save(commit=False)
            lisaa_kurssi.kayttaja = request.user
            lisaa_kurssi.save()
            return redirect('TimeManagementToolApp:kurssit')

    #Näytetään tyhjä lomake
    context = {'form': form}
    return render(request, 'TimeManagementToolApp/lisaa_kurssi.html', context)

@login_required
def lisaa_tehtava(request, kurssi_id):
    #Lisää uusi tehtävä tietyn kurssin alle
    kurssi = Kurssi.objects.get(id=kurssi_id)

    if request.method != 'POST':
        #Luo tyhjä lomake
        form = TehtForm()

    else:
        #Käsitellään data
        form = TehtForm(data=request.POST or None)
        if form.is_valid():
            lisaa_tehtava = form.save(commit=False)
            lisaa_tehtava.kurssi = kurssi
            lisaa_tehtava.save()
            return redirect('TimeManagementToolApp:kurssi', kurssi_id=kurssi_id)

    #Näytetään tyhjä lomake
    context = {'kurssi': kurssi, 'form':form}
    return render(request, 'TimeManagementToolApp/lisaa_tehtava.html', context)

@login_required
def muokkaa_tehtava(request, teht_id):
    #Muokataan olemassa olevaa tehtävää
    teht= Teht.objects.get(id=teht_id)
    kurssi = teht.kurssi
    # Suojataan muokkausoikeus vain oikealle käyttäjälle
    if kurssi.kayttaja != request.user:
        raise Http404

    if request.method != 'POST':
        #Esitäytetty alkuperäisen tehtävän sisällön mukaan
        form = TehtForm(instance=teht)

    else:
        #Käsitellään muutokset
        form = TehtForm(instance=teht, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('TimeManagementToolApp:kurssi', kurssi_id =kurssi.id)
        
    context = {'teht': teht, 'kurssi': kurssi, 'form': form}
    return render(request, 'TimeManagementToolApp/muokkaa_tehtava.html', context)

@login_required
def poista_tehtava(request, teht_id):
    #poistetaan tehtävä
    teht = Teht.objects.get(id=teht_id)
    kurssi = teht.kurssi
    if kurssi.kayttaja != request.user:
        raise Http404
    if request.method == 'POST':
        teht.delete()
        return redirect('TimeManagementToolApp:kurssi', kurssi_id=kurssi.id)
    return render(request, 'TimeManagementToolApp/poista_tehtava.html', {'teht': teht})

@login_required
def poista_kurssi(request, kurssi_id):
    #poistetaan kurssi
    kurssi = Kurssi.objects.get(id=kurssi_id)
    if kurssi.kayttaja != request.user:
        raise Http404
    if request.method == 'POST':
        kurssi.delete()
        return redirect('TimeManagementToolApp:kurssit')

TimeManagementTool/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def rekist(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('TimeManagementToolApp:index')
    
    context = {'form': form}
    return render(request, 'registration/rekist.html', context)

TimeManagementTool/TimeManagementToolApp/templates/TimeManagementToolApp/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        /* linkkien muokkaus */
        p a {
            color: #6495ED; /* linkin väri */
            text-decoration: none; /* poistetaan alaviiva */
            transition: color 0.3s; /* vaihtoaika */
        }

        /* linkin vaihtoväri */
        p a:hover {
            color: #ff1493; /* väri hiiren ollessa päällä */
        }
        p.message {
            color: #000000; /* halutun viestin muotoilu */
            font-weight: bold;
        }
    </style>
</head>
<body>
<p>
    <a href="{% url 'TimeManagementToolApp:index' %}">Ajanhallinta</a> -
    <a href="{% url 'TimeManagementToolApp:kurssit' %}">Kurssit</a> -
    {% if user.is_authenticated %}
        Hei, {{ user.username }}.
    {% else %}
        <a href="{% url 'accounts:rekist' %}">Rekisteröidy</a> -
        <a href="{% url 'accounts:login' %}">Kirjaudu</a>
    {% endif %}
</p>

{% if not user.is_authenticated %}
    <p class="message">Teidän täytyy rekisteröityä/kirjautua käyttääksenne sivustoa</p>
{% endif %}

{% block content %}{% endblock content %}

{% if user.is_authenticated %}
    <hr />
    <form action="{% url 'accounts:logout' %}" method='post'>
        {% csrf_token %}
        <button name='submit'>Kirjaudu ulos</button>
    </form>
{% endif %}

</body>
</html>

TimeManagementTool/TimeManagementToolApp/templates/TimeManagementToolApp/index.html
{% extends 'TimeManagementToolApp/base.html' %} <!-- Hakee pohjan 'TimeManagementToolApp/base.html' tiedostosta -->

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Kurssit</title> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> <!-- Lisää Bootstrapin -->
    <style>
        body {
            padding: 20px;
        }
        .grid-container {
            display: grid; /* Muuttaa elementin grid muotoon */
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); /* Määrittää sarakkeet gridille */
            grid-gap: 20px; /* Väli gridin elementtien välillä */
        }
        .kurssi-header {
            background-color: #e3f2fd; /* Asettaa taustavärin kurssin otsikolle */
            padding: 15px;
            border-radius: 5px; /* Pyöristää reunat */
            box-shadow: 0 4px 8px rgba(0,0,0,0.1); /* Asettaa varjon laatikolle */
            cursor: pointer;
            transition: background-color 0.3s;
            text-decoration: none; /* Alaviivat pois */
            color: inherit;
        }
        .kurssi-header:hover { /* Muuttaa taustavärin hiiren ollessa blokin yllä */ 
            background-color: #d4eaf7;
            text-decoration: none;
        }
        .deadline {
            color: #ff0000; /* Asettaa dealine-pvm:n värin punaiseksi */
        }
    </style>
</head>
<body>
    <h1>Kurssit</h1> 
    <div class="grid-container">
        {% for kurssi in kurssit %} 
            <a href="{% url 'TimeManagementToolApp:kurssi' kurssi.id %}" class="kurssi-header">
                <h2>{{ kurssi.kurssi }}</h2> <!-- Näyttää kurssin nimen -->
                <ul class="list-unstyled">
                    {% for teht in kurssi.teht_set.all|dictsort:"dedis" %} 
                        <li>
                            <p><strong>{{ teht.teht }} :</strong></p> <!-- Näyttää tehtävän nimen -->
                            {% if teht.dedis %} <!-- Tarkistaa, onko tehtävällä deadline -->
                                <p>Deadline: <span class="deadline">{{ teht.dedis|date:"d.m.Y H:i" }}</span></p> <!-- Näyttää deadlinen -->
                            {% endif %}
                        </li>
                    {% empty %} <!-- Jos tehtäviä ei ole -->
                        <li>Ei lisättyjä tehtäviä tälle kurssille</li> <!-- Näyttää viestin, että tehtäviä ei ole lisätty -->
                    {% endfor %}
                </ul>
            </a>
        {% endfor %}
    </div>
</body>
</html>
{% endblock content %}

TimeManagementTool/TimeManagementToolApp/templates/TimeManagementToolApp/kurssi.html
{% extends 'TimeManagementToolApp/base.html' %} <!-- Hakee pohjan 'TimeManagementToolApp/base.html' tiedostosta -->

{% block content %}


<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: 'Arial', sans-serif; /* Asettaa tekstin fontin */
            background-color: #f4f4f4; /* Taustaväri */
            line-height: 1.6; /* Rivien korkeus */
        }
        .note-container {
            background-color: #e3f2fd; /* Taustaväri muistiinpanoille */
            padding: 20px;
            margin-top: 10px; /* Ylämarginaali */
            border-radius: 8px; /* Reunojen pyöristys */
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05); /* Varjostus */
            max-width: 600px; /* Maksimileveys */
            margin: auto; /* Keskittää elementin */
        }
        .note-header {
            font-size: 28px;
            font-weight: 600; 
            color: #333333;
            margin-bottom: 10px; /* Alareunan marginaali */
        }
        .note-list {
            list-style: none; /* Poistaa listamerkit */
            padding: 0;
            border-top: 1px solid #eaeaea; /* Ylärivin reunaviiva */
        }
        .note-list li {
            padding: 0px 0; 
            border-bottom: 1px solid #eaeaea; /* Alareunan reunaviiva */
        }
        .note-list li:last-child {
            border-bottom: none; /* Poistaa viimeisen listaelementin alareunan reunaviivan */
        }
        .note-text {
            margin: 0; /* Ei marginaalia */
            color: #555555; /* Tekstin väri */
        }
        .no-tasks {
            text-align: center; /* Keskittää tekstin */
            color: #888888; /* Tekstin väri, kun tehtäviä ei ole */
        }
        .deadline {
            color: #ff0000; /* Värjää deadline-tekstin punaiseksi */
        }
    </style>
</head>
<body>

    <div class="note-container">
        <p class="note-header">Kurssi: {{ kurssi.kurssi }}</p>
        <p>
            <a href="{% url 'TimeManagementToolApp:lisaa_tehtava' kurssi.id %}">Lisää tehtävä</a>
        </p>
        <p class="note-header">Tehtävät:</p> 
        
        <ul class="note-list">
            {% for teht in kurssi.teht_set.all|dictsort:"dedis" %} <!-- Käy läpi kurssin tehtävät ja järjestää ne deadlinen mukaan -->
                <li>
                    <p class="note-text">{{ teht.teht|linebreaks }}</p> <!-- Näyttää tehtävän tekstin -->
                    {% if teht.dedis %} <!-- Tarkistaa, onko tehtävällä deadline -->
                        <p>Deadline: <span class="deadline">{{ teht.dedis|date:"d.m.Y H:i" }}</span>
                            </p> <!-- Näyttää deadlinen -->
                            <a href="{% url 'TimeManagementToolApp:muokkaa_tehtava' teht.id %}">Muokkaa tehtävää</a></p>
                    {% endif %}
                </li>
            {% empty %} <!-- Jos tehtäviä ei ole -->
                <p class="no-tasks">Ei lisättyjä tehtäviä tälle kurssille</p> <!-- Näyttää viestin, että tehtäviä ei ole -->
            {% endfor %}
        </ul>
    </div>
</body>
</html>

{% endblock content %}

TimeManagementTool/TimeManagementToolApp/templates/TimeManagementToolApp/kurssit.html
{% extends 'TimeManagementToolApp/base.html' %} <!-- Hakee pohjan 'TimeManagementToolApp/base.html' tiedostosta -->

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <style>
        .course-link {
            display: block;
            background-color: #e3f2fd; /* Taustaväri */
            padding: 10px;
            margin-bottom: 6px; /* Alareunan marginaali */
            margin-top: 10px;  /* yläreunan marginaali */
            border-radius: 5px; /* Reunojen pyöristys */
            text-decoration: none; /* Poistaa tekstistä korostuksen */
            color: black; /* Tekstin väri */
            box-shadow: 0 4px 8px rgba(0,0,0,0.1); /* Laatikon varjostus */
            transition: background-color 0.3s, box-shadow 0.3s; /* Värin ja varjostuksen siirtymäefektit */
            font-size: 16px;
        }
        .course-link:hover {
            background-color: #d1e8ff; /* Taustaväri kun hiiri on linkin päällä */
            box-shadow: 0 6px 12px rgba(0,0,0,0.15); /* Varjostus kun hiiri on linkin päällä */
        }
        .add-course-link {
            
            color: #6495ed; /* Linkin tekstin väri*/
            padding: 6px;
            border-radius: 5px;
            text-decoration: none;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            transition: background-color 0.3s, box-shadow 0.3s;
        }
        .add-course-link:hover {
            color: #ff1493; /* väri hiiren ollessa päällä */
        }
        .delete-course-button {
            color: #ff0000;
            font-size: 10px;
            background-color: #ffffff; /* Taustaväri */
            transition: color 0.3s;
            border: none;
            cursor: pointer;
        }
        .delete-course-button:hover {
            color: #b22222;
        }
    
    </style>
</head>
<body>
    <h1>Kurssit</h1>


    <a class="add-course-link" href="{% url 'TimeManagementToolApp:lisaa_kurssi' %}">Lisää uusi kurssi</a>
    <ul style="list-style: none; padding: 0;"> <!-- Lista ilman tyyliteltyjä listamerkkejä ja ilman paddingia -->
        {% for kurssi in kurssit %}
    <li>
        <a class="course-link" href="{% url 'TimeManagementToolApp:kurssi' kurssi.id %}">
            {{ kurssi.kurssi }}
        </a>
        <!-- Kurssin poisto -->
        <form action="{% url 'TimeManagementToolApp:poista_kurssi' kurssi.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class ="delete-course-button" onclick="return confirm('Haluatko varmasti poistaa tämän kurssin?');">Poista Kurssi</button>
        </form>
    </li>
{% empty %}
    <li>Kursseja ei ole vielä lisätty</li>
{% endfor %}
    </ul>
</body>
</html>

{% endblock content %} <!-- Päättää sisältölohkon -->

TimeManagementTool/TimeManagementToolApp/templates/TimeManagementToolApp/lisaa_kurssi.html
{% extends 'TimeManagementToolApp/base.html' %}

{% block content %}
    <style>
        .add-course-header {
            color: #6495ed; /* pääväri */
            transition: color 0.3s; /
        }
        .add-course-header:hover {
            color: #ff1493; /* hiiren alla väri */
        }
    </style>

    <p class="add-course-header">Lisää kurssi:</p>

    <form action="{% url 'TimeManagementToolApp:lisaa_kurssi' %}" method='post'>
        {% csrf_token %}
        {{ form.as_div }}
        <button name="submit">Lisää kurssi</button>
    </form>
{% endblock content %}

TimeManagementTool/TimeManagementToolApp/templates/TimeManagementToolApp/lisaa_tehtava.html
{% extends 'TimeManagementToolApp/base.html' %}

{% block content %}

    <p><a href="{% url 'TimeManagementToolApp:kurssi' kurssi.id %}">{{ kurssi }}</a></p>

    <p>Lisää uusi tehtävä:</p>

    <form method='post'>
        {% csrf_token %}
        <div>
            <p>Lisää tehtävä:</p>
            {{ form.teht }}
        </div>
        <div>
            <p>Lisää deadline:</p>
            {{ form.dedis }}
        </div>
        <div>
            <p>Merkikse tehdyksi:</p>
            {{ form.valmis }}
        </div>        
        <button name = "submit">Lisää tehtävä</button>
    </form>

{% endblock content %}

TimeManagementTool/TimeManagementToolApp/templates/TimeManagementToolApp/muokkaa_tehtava.html
{% extends 'TimeManagementToolApp/base.html' %}

{% block content %}

<p><a href="{% url 'TimeManagementToolApp:kurssi' kurssi.id %}">{{ kurssi }}</a></p>

<!-- Tehtävän muokkaus -->
<form method='post'>
    {% csrf_token %}
    <div>
        <p>Muokkaa tehtävää:</p>
        {{ form.teht }}
    </div>
    <div>
        <p>Vaihda deadline:</p>
        {{ form.dedis }}
    </div>
    <div>
        <p>Merkikse tehdyksi:</p>
        {{ form.valmis }}
    </div>      
    <button name="submit">Tallenna</button>
</form>

<!-- Tehtävän poisto -->
<form action="{% url 'TimeManagementToolApp:poista_tehtava' teht.id %}" method="post">
    {% csrf_token %}
    <button type="submit" onclick="return confirm('Haluatko varmasti poistaa tämän tehtävän?');" style="color: red;">Poista Tehtävä</button>
</form>

{% endblock content %}

TimeManagementTool/TimeManagementToolApp/templates/TimeManagementToolApp/tehtava.html
{% extends 'TimeManagementToolApp/base.html' %}

{% block content %}

    <p>Tehtävä: {{tehtava.tehtava}} </p>
    <p>Kurssilla <a href="{% url 'TimeManagementToolApp:tehtava' tehtava.kurssi %}">
        {{ tehtava.kurssi }}</a> </p>

    <ul>
       <p>Deadline: {{ deadline.tehtava }}</p>
       <p>Tehty: {{ valmis}}</p>

        {% empty %}
            <li>Kursseja ei ole vielä lisätty</li>
        {% endfor %}
    </ul>

{% endblock content %}